apiVersion: v1
kind: Service
metadata:
  name: quorum-tessera-node-1-service
spec:
  type: ClusterIP
  selector:
    io.kompose.service: quorum-tessera-node-1
  ports:
  - name:  tessera-p2p
    port: 9001
    protocol: TCP
    targetPort: 9001
  - name: tessera-3party
    port: 9002
    protocol: TCP
    targetPort: 9002
  - name:  tessera-q2t
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name:  rpc
    port: 22000
    targetPort: 22000
  - name:  raftport
    port: 50401
    targetPort: 50401
  - name:  bootnode
    port: 21000
    targetPort: 21000
